name: IMAGE COMBINED

on:
  workflow_dispatch:
  # schedule:
    # - cron: '30 11 * * *'   # Runs at 5:00 PM IST
    # - cron: '30 15 * * *'   # Runs at 9:00 PM IST

jobs:
  update-counter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      image_number: ${{ steps.increment.outputs.image_number }}
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: EiraRajput/SOCIAL_MEDIA
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          sparse-checkout: |
            COUNTER/
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Run your Python script and expose the updated counter
      - name: Increment Counter
        id: increment
        run: |
          python3 COUNTER/counter_image.py
          IMAGE_NUMBER=$(cat COUNTER/counter_image.txt)
          echo "image_number=$IMAGE_NUMBER" >> $GITHUB_OUTPUT
          echo "Updated counter_image.txt to: $IMAGE_NUMBER"

      # Check if counter_image.txt has been modified, pull, and push the modified changes.
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add COUNTER/counter_image.txt
          git commit -m "Update counter_image.txt after processing" || echo "No changes to commit"
          git pull --rebase origin main || echo "No changes to pull"
          git push || echo "No changes to push"

  threads-image:
    needs: update-counter
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: EiraRajput/SOCIAL_MEDIA
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          sparse-checkout: |
            AI_MODELS/
            THREADS/
            COUNTER/counter_image.txt
            requirements.txt
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        run: python3 THREADS/thread_image.py

  facebook-image:
    needs: update-counter
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: EiraRajput/SOCIAL_MEDIA
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          sparse-checkout: |
            AI_MODELS/
            FACEBOOK/
            COUNTER/counter_image.txt
            requirements.txt
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        run: python3 FACEBOOK/facebook_image.py

  instagram-image:
    needs: update-counter
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: EiraRajput/SOCIAL_MEDIA
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          sparse-checkout: |
            AI_MODELS/
            INSTAGRAM/
            COUNTER/counter_image.txt
            requirements.txt
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        run: python3 INSTAGRAM/instagram_image.py